"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { FlavorId } from "../flavors/flavors";
import type { SpiritId } from "../spirits/spirits";
import LanguageToggle from "../language-toggle";
import EndTonightControl from "../end-tonight-control";
import TonightSignal, { getTonightSignalNumber } from "../tonight-signal";
import { readTonightCocktailSession } from "@/lib/cocktails/tonight-session";
import { RealtimeMatchService } from "@/lib/second/realtime-match-service";
import type { CanonicalMatchState } from "@/server/realtime/socket-events";
import { useSecondProfile } from "@/lib/second/use-second-profile";
import { localizeEnergy, useI18n } from "@/lib/i18n";
import { energyOptions } from "@/lib/second/profile";

const primary = "second-primary";
const secondary = "second-secondary";
const signals = (profile: ReturnType<typeof useSecondProfile>["profile"], cocktail: ReturnType<typeof readTonightCocktailSession>, spirit: SpiritId, flavor: FlavorId) => ({ nickname: profile.nickname ?? "", age: profile.age ?? 0, energy: profile.energy ?? "open", ...(profile.mbti ? { mbti: profile.mbti } : {}), spirit: cocktail?.spirit ?? spirit, flavor: cocktail?.flavor ?? flavor, cocktailId: cocktail?.result.recipe.id ?? "", cocktailName: cocktail?.result.recipe.name ?? "", ageBand: 0 });

function Timer({ seconds }: { seconds: number }) {
  return <p role="timer" aria-label={`${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`} className="font-[family-name:var(--font-display)] text-[clamp(4.8rem,24vw,7rem)] leading-none tracking-[-.08em] tabular-nums text-stone-100">{String(Math.floor(seconds / 60)).padStart(2, "0")}:{String(seconds % 60).padStart(2, "0")}</p>;
}

export default function RealtimeMatchExperience({ spirit, flavor }: { spirit: { id: SpiritId; name: string }; flavor: { id: FlavorId; name: string } }) {
  const { profile, isHydrated } = useSecondProfile();
  const { language } = useI18n(); const zh = language === "zh";
  const [consented, setConsented] = useState(false); const [error, setError] = useState(""); const [secondsLeft, setSecondsLeft] = useState(300); const [queueSeconds, setQueueSeconds] = useState(0);
  const [state, setState] = useState<CanonicalMatchState>({ stage: "idle", serverNow: new Date().toISOString() });
  const service = useMemo(() => new RealtimeMatchService(), []); const cocktail = isHydrated ? readTonightCocktailSession() : null;
  const href = `/flavors/next?${new URLSearchParams({ spirit: spirit.id, flavor: flavor.id }).toString()}`;
  const c = (en: string, cn: string) => zh ? cn : en; const candidate = state.candidate;
  const energy = candidate ? energyOptions.find((item) => item.id === candidate.energy) : null;
  const num = cocktail ? getTonightSignalNumber(cocktail.result.recipe.id, spirit.id, flavor.id) : undefined;
  useEffect(() => {
    const off = service.subscribe(setState);
    const offError = service.subscribeError(() => setError(language === "zh" ? "今晚的连接暂时不可用。请稍后再试。" : "Tonight’s connection is temporarily unavailable. Please try again shortly."));
    void service.restore().catch(() => undefined);
    return () => { off(); offError(); service.disconnect(); };
  }, [language, service]);
  useEffect(() => { if (state.stage !== "connection" || !state.endsAt) return; const tick = () => setSecondsLeft(Math.max(0, Math.ceil((new Date(state.endsAt!).getTime() - Date.now()) / 1000))); tick(); const id = window.setInterval(tick, 1000); return () => clearInterval(id); }, [state.endsAt, state.stage]);
  useEffect(() => { if (state.stage !== "waiting" || !state.enteredQueueAt) return; const tick = () => setQueueSeconds(Math.max(0, Math.floor((Date.now() - new Date(state.enteredQueueAt!).getTime()) / 1000))); tick(); const id = window.setInterval(tick, 1000); return () => clearInterval(id); }, [state.enteredQueueAt, state.stage]);
  const action = (work: () => Promise<void>) => { setError(""); void work().catch((reason) => setError(reason instanceof Error ? reason.message : c("Realtime request failed.", "实时匹配请求未完成。"))); };
  const join = () => { if (!cocktail) return setError(c("Save tonight’s cocktail before joining.", "请先保存今晚的 Cocktail。")); action(() => service.start(signals(profile, cocktail, spirit.id, flavor.id))); };
  const signal = (stage: "reveal" | "searching" | "mutual", label: string, compact = false) => <TonightSignal stage={stage} spirit={spirit.id} flavor={flavor.id} cocktailNumber={num} partnerSeed={candidate?.nickname} compact={compact} label={label} className="mx-auto mb-7 w-52" />;

  return <main data-stage={state.stage} className="second-match min-h-dvh overflow-x-hidden bg-[#080808] px-5 pb-[max(2rem,env(safe-area-inset-bottom))] pt-[max(1.25rem,env(safe-area-inset-top))] sm:px-6"><div className="mx-auto w-full max-w-md">
    <header className="flex min-h-11 items-center justify-between gap-3"><Link href={href} className="inline-flex min-h-11 items-center text-[.62rem] font-semibold uppercase tracking-[.14em] text-white/48">← {c("My drink", "我的酒")}</Link><div className="flex items-center gap-2"><LanguageToggle /><EndTonightControl /></div></header>
    <section className="second-stage flex min-h-[calc(100svh-5rem)] flex-col justify-center py-7">
      {state.stage === "idle" && <div><p className="second-micro text-amber-100/58">SECOND ACT</p><h1 className="second-screen-title mt-5 text-stone-100">{c("Before we begin", "在开始之前")}</h1><ul className="mt-7 space-y-3 border-y border-white/[.12] py-6 text-sm leading-6 text-white/58"><li>{c("They will see a limited Tonight Profile.", "对方会看到有限的 Tonight Profile。")}</li><li>{c("No contact details are shared.", "不会看到联系方式。")}</li><li>{c("A meeting area appears only after mutual yes.", "只有双方都愿意见面后才会出现 Meeting Area。")}</li><li>{c("You can leave tonight’s matching at any time.", "你随时可以离开今晚的匹配。")}</li></ul><label className="mt-6 flex min-h-11 cursor-pointer gap-3 text-xs leading-5 text-white/54"><input checked={consented} onChange={(e) => setConsented(e.target.checked)} type="checkbox" className="mt-0.5 h-4 w-4 accent-[#eadfce]" /><span>{c("I understand these boundaries and want to start looking.", "我理解这些边界，并愿意开始寻找。")}</span></label><button disabled={!consented} className={`${primary} mt-6`} onClick={join}>{c("Start looking", "开始寻找")}</button><Link href={href} className={`${secondary} mt-3`}>{c("Back to my drink", "返回我的酒")}</Link></div>}
      {state.stage === "waiting" && <div className="text-center" role="status" aria-live="polite">{signal("reveal", c("One signal waiting", "一个信号正在等待"))}<p className="second-micro text-amber-100/58">WAITING</p><p className="mt-2 font-[family-name:var(--font-display)] text-4xl tabular-nums text-stone-100">{String(Math.floor(queueSeconds / 60)).padStart(2, "0")}:{String(queueSeconds % 60).padStart(2, "0")}</p><h1 className="second-screen-title mt-6 text-stone-100">{c("Looking for another signal tonight", "正在寻找今晚的另一个信号")}</h1><p className="mx-auto mt-5 max-w-xs text-sm leading-6 text-white/48">{c("You don’t need to watch the screen. We’ll let you know when someone appears.", "不用一直盯着屏幕。有人出现时，我们会告诉你。")}</p><button className={`${secondary} mx-auto mt-8 max-w-xs`} onClick={() => action(() => service.cancelQueue())}>{c("Cancel", "取消等待")}</button></div>}
      {state.stage === "candidate" && candidate && <div>{signal("searching", c("Two signals drawing closer", "两个信号正在靠近"))}<p className="second-micro text-amber-100/58">{c("ONE POSSIBLE INTRODUCTION", "一次可能的介绍")}</p><h1 className="second-screen-title mt-4 text-stone-100">{c("Someone appeared tonight", "今晚，有一个人出现了")}</h1><p className="mt-5 text-lg text-white/86">{candidate.nickname} <span className="text-white/36">·</span> {candidate.age}</p><p className="mt-2 text-xs font-semibold tracking-[.15em] text-white/42">{energy ? localizeEnergy(energy.id, energy.label, language) : candidate.energy}</p><div className="mt-6 border-y border-white/[.13] py-5"><p className="second-micro text-amber-100/58">{c("WHY YOU TWO", "为什么是你们")}</p><ul className="mt-3 space-y-2 text-sm leading-6 text-white/66">{candidate.reasons.map((reason) => <li key={reason.id}>— {reason[language]}</li>)}</ul></div><div className="mt-5 border-l border-amber-100/45 py-1 pl-4"><p className="second-micro text-white/40">{c("OPENING SIGNAL", "开场信号")}</p><p className="mt-2 text-[1rem] leading-6 text-stone-100/88">“{candidate.openingPrompt[language]}”</p></div><div className="mt-7 grid gap-3"><button className={primary} onClick={() => action(() => service.accept())}>{c("I’d meet them", "愿意见面")}</button><button className={secondary} onClick={() => action(() => service.pass())}>{c("Pass", "暂时不见")}</button><button className="min-h-11 text-xs text-white/45 underline underline-offset-4" onClick={() => action(() => service.block())}>{c("Do not show this person again tonight", "今晚不再匹配此人")}</button></div></div>}
      {state.stage === "waiting_for_other" && candidate && <div className="text-center">{signal("searching", c("Your signal is waiting", "你的信号正在等待"))}<p className="second-micro text-amber-100/58">WAITING FOR THEM</p><h1 className="second-screen-title mt-5 text-stone-100">{c("You said yes", "你愿意见面了")}</h1><p className="mx-auto mt-5 max-w-xs text-sm leading-6 text-white/50">{c("Now leave the choice with them. If they agree too, Second will tell you where to meet.", "现在，把选择留给对方。如果对方也愿意，Second 会告诉你们在哪里见面。")}</p><button className={`${secondary} mx-auto mt-8 max-w-xs`} onClick={() => action(() => service.leave())}>{c("Leave tonight’s match", "离开今晚的匹配")}</button></div>}
      {state.stage === "mutual" && candidate && state.meetingArea && <div className="text-center">{signal("mutual", c("Two signals, one shared mark", "两个信号汇成一个共同标记"))}<p className="second-micro text-amber-100/58">SECOND ACT · MUTUAL</p><h1 className="second-screen-title mt-5 text-stone-100">{c("You both said yes", "你们都愿意见面")}</h1><p className="mt-4 text-sm text-white/55">{c("Now make it real.", "接下来，去真实世界里找到彼此。")}</p><div className="mt-7 border-y border-white/[.14] py-6"><p className="second-micro text-white/42">{c("MEETING AREA", "见面区域")}</p><p className="mt-3 font-[family-name:var(--font-display)] text-3xl text-stone-100">{zh ? state.meetingArea.labelZh : state.meetingArea.label}</p><p className="mt-3 text-xs text-white/43">{c("This broad area comes from the venue server.", "这个宽泛区域由现场服务端提供。")}</p></div><button className={`${primary} mt-7`} onClick={() => action(() => service.beginConnection())}>{c("We found each other", "我们找到了")}</button></div>}
      {state.stage === "connection" && candidate && <div className="flex flex-1 flex-col justify-between py-7 text-center"><p className="second-micro text-amber-100/58">SECOND ACT</p>{signal("mutual", c("Shared signal", "共同信号"), true)}<div><Timer seconds={secondsLeft} /><p className="mt-5 text-sm text-white/58">{candidate.nickname} <span className="mx-2 text-white/28">×</span> {profile.nickname || c("You", "你")}</p><div className="mt-8 border-l border-amber-100/40 py-1 pl-4 text-left"><p className="second-micro text-white/40">{c("START HERE", "从这里开始")}</p><p className="mt-2 text-[.98rem] leading-6 text-stone-100/88">“{candidate.openingPrompt[language]}”</p></div></div><p className="mt-9 text-sm text-white/48">{c("Now put your phone down.", "现在，把手机放下。")}</p><button className="mx-auto mt-6 min-h-11 text-xs text-white/42 underline underline-offset-4" onClick={() => action(() => service.report("unsafe"))}>{c("Report / get help", "举报 / 求助")}</button></div>}
      {state.stage === "time_up" && <div className="text-center"><p className="second-micro text-amber-100/58">TIME’S UP</p><h1 className="second-screen-title mt-5 text-stone-100">{c("Five minutes are up.", "五分钟到了。")}</h1><p className="mt-5 text-sm text-white/55">{c("Would you like to keep the story going?", "还想继续聊吗？")}</p><div className="mt-8 grid gap-3"><button className={primary} onClick={() => action(() => service.continueConnection())}>{c("Keep the story going", "继续这个故事")}</button><button className={secondary} onClick={() => action(() => service.finishConnection())}>{c("That’s enough for tonight", "到这里就好")}</button></div></div>}
      {state.stage === "waiting_for_continue" && <div className="text-center">{signal("mutual", c("Shared signal waiting", "共同信号正在等待"), true)}<p className="second-micro text-amber-100/58">WAITING FOR THEM</p><h1 className="second-screen-title mt-5 text-stone-100">{c("You’d like to continue", "你愿意继续")}</h1><p className="mt-5 text-sm text-white/50">{c("Now leave the choice with them.", "现在，把选择留给对方。")}</p></div>}
      {state.stage === "continuing" && <div className="text-center">{signal("mutual", c("Shared signal", "共同信号"), true)}<p className="second-micro text-amber-100/58">SECOND ACT</p><h1 className="second-screen-title mt-5 text-stone-100">{c("Let the story continue.", "让故事继续。")}</h1><p className="mt-5 text-sm leading-6 text-white/55">{c("Put the phone away. The rest is yours.", "把手机放下，剩下的故事交给你们。")}</p><Link href={href} className={`${primary} mt-8`}>{c("Back to my drink", "回到我的酒")}</Link></div>}
      {state.stage === "ended" && <div className="text-center"><p className="second-micro text-amber-100/58">SECOND</p><h1 className="second-screen-title mt-5 text-stone-100">{c("The night continues, so does the story.", "夜晚还在继续，故事也是。")}</h1><div className="mt-8 grid gap-3"><button className={primary} onClick={join}>{c("Meet someone else", "再认识一个人")}</button><Link href={href} className={secondary}>{c("Back to my drink", "回到我的酒")}</Link></div></div>}
      {error && <p role="alert" className="mt-6 text-sm text-rose-200/80">{error}</p>}
    </section>
  </div></main>;
}
